import type { Card, GameState, Player, Position, TableObject } from '../types/game';
import { id } from '../utils/id';
import { shuffle } from '../utils/shuffle';

export type Action =
 | { type: 'setEditorMode'; mode: 'play'|'board' } | { type: 'createBoard'; name: string } | { type: 'updateBoard'; id: string; changes: Partial<GameState['boards'][number]> } | { type: 'createShape'; boardId: string; position: Position; isSpace: boolean; shapeType?: 'rectangle'|'roundedRectangle'|'circle' } | { type: 'moveShape'; id: string; position: Position } | { type: 'updateShape'; id: string; changes: Partial<GameState['boardShapes'][number]> } | { type: 'deleteShape'; id: string } | { type: 'duplicateShape'; id: string } | { type: 'generateSpaces'; boardId: string; count: number; spacing: number; autoNumber: boolean; start: number } | { type: 'createLine'; boardId: string; start: Position; end: Position } | { type: 'moveLine'; id: string; start: Position; end: Position } | { type: 'deleteLine'; id: string }
 | { type: 'addPlayer'; player: Player } | { type: 'updatePlayer'; id: string; changes: Partial<Player> } | { type: 'deletePlayer'; id: string } | { type: 'exchangeCards'; firstPlayerId: string; firstCardIds: string[]; secondPlayerId: string; secondCardIds: string[] } | { type: 'importSetup'; players: Player[]; cards: Card[] }
 | { type: 'createCards'; suits: string[]; values: string[]; copies: number } | { type: 'addCards'; suit: string; value: string; copies: number; position?: Position }
 | { type: 'updateCard'; id: string; changes: Partial<Card> } | { type: 'deleteCard'; id: string } | { type: 'deleteCards'; ids: string[] }
 | { type: 'createDeck'; name: string; cardIds: string[]; position: Position } | { type: 'deleteDeck'; id: string } | { type: 'shuffleDeck'; id: string } | { type: 'drawCard'; deckId: string } | { type: 'drawCardToTable'; deckId: string } | { type: 'dealCards'; deckId: string; count: number } | { type: 'dealEvenly'; deckId: string; count: number } | { type: 'returnToDeck'; cardId: string; deckId: string }
 | { type: 'moveCardToTable'; cardId: string; position: Position; snap?: boolean; faceDown?: boolean } | { type: 'moveCardToHand'; cardId: string; playerId: string } | { type: 'moveObject'; id: string; position: Position; snap?: boolean } | { type: 'flipTableCard'; objectId: string } | { type: 'selectPlayer'; id: string }
 | { type: 'addDie'; position: Position } | { type: 'rollDie'; id: string } | { type: 'addToken'; color: string; value: number; position: Position } | { type: 'updateToken'; id: string; changes: { color?: string; value?: number } } | { type: 'deleteToken'; id: string }
 | { type: 'addPawn'; color: string; ownerPlayerId?: string; position?: Position } | { type: 'updatePawn'; id: string; changes: { color?: string; ownerPlayerId?: string } } | { type: 'deletePawn'; id: string } | { type: 'changeScore'; id: string; amount: number };

const object = (type: TableObject['type'], refId: string, position: Position, zIndex: number): TableObject => ({ id: id('obj'), type, refId, position, zIndex });
const objectSizes:Record<TableObject['type'],{width:number;height:number}>={card:{width:84,height:116},deck:{width:92,height:118},die:{width:62,height:62},token:{width:65,height:65},pawn:{width:44,height:58}};
const clampObjectPosition=(state:GameState,type:TableObject['type'],position:Position)=>{const board=state.boards[0],size=objectSizes[type];if(!board)return{x:Math.max(0,position.x),y:Math.max(0,position.y)};return{x:Math.min(Math.max(0,board.width-size.width),Math.max(0,position.x)),y:Math.min(Math.max(0,board.height-size.height),Math.max(0,position.y))}};
const removeCardEverywhere = (s: GameState, cardId: string) => ({ ...s, players: s.players.map(p => ({ ...p, hand: p.hand.filter(x => x !== cardId) })), decks: s.decks.map(d => ({ ...d, cardIds: d.cardIds.filter(x => x !== cardId) })), tableObjects: s.tableObjects.filter(o => !(o.type === 'card' && o.refId === cardId)) });
export function reducer(state: GameState, action: Action): GameState {
 switch(action.type) {
  case 'setEditorMode': return { ...state, editorMode: action.mode };
  case 'createBoard': { const board={id:id('board'),name:action.name,width:2700,height:1800,backgroundColor:'#4f8567',gridSize:10,gridEnabled:true,snapEnabled:true}; return {...state,boards:[...state.boards,board]}; }
  case 'updateBoard': return {...state,boards:state.boards.map(b=>b.id===action.id?{...b,...action.changes}:b)};
  case 'createShape': { const shape={id:id('shape'),boardId:action.boardId,shapeType:action.shapeType??'roundedRectangle',position:action.position,width:64,height:64,fillColor:'#fffdf5',strokeColor:'#56685d',strokeWidth:2,label:'',note:'',isSpace:action.isSpace,zIndex:state.nextZ};return {...state,boardShapes:[...state.boardShapes,shape],nextZ:state.nextZ+1}; }
  case 'moveShape': return {...state,boardShapes:state.boardShapes.map(s=>s.id===action.id?{...s,position:action.position}:s)};
  case 'updateShape': return {...state,boardShapes:state.boardShapes.map(s=>s.id===action.id?{...s,...action.changes}:s)};
  case 'deleteShape': return {...state,boardShapes:state.boardShapes.filter(s=>s.id!==action.id),boardLines:state.boardLines.filter(l=>(l as any).start?.shapeId!==action.id&&(l as any).end?.shapeId!==action.id)};
  case 'duplicateShape': { const source=state.boardShapes.find(s=>s.id===action.id);if(!source)return state;return {...state,boardShapes:[...state.boardShapes,{...source,id:id('shape'),position:{x:source.position.x+20,y:source.position.y+20},zIndex:state.nextZ}],nextZ:state.nextZ+1}; }
  case 'generateSpaces': { const shapes=Array.from({length:action.count},(_,i)=>({id:id('shape'),boardId:action.boardId,shapeType:'roundedRectangle' as const,position:{x:30+i*(64+action.spacing),y:50},width:64,height:64,fillColor:'#fffdf5',strokeColor:'#56685d',strokeWidth:2,label:action.autoNumber?String(action.start+i):'',note:'',isSpace:true,zIndex:state.nextZ+i}));return {...state,boardShapes:[...state.boardShapes,...shapes],nextZ:state.nextZ+shapes.length}; }
  case 'createLine': { const line={id:id('line'),boardId:action.boardId,start:action.start,end:action.end,strokeWidth:2,lineStyle:'solid' as const,arrow:'end' as const,zIndex:state.nextZ};return {...state,boardLines:[...state.boardLines,line],nextZ:state.nextZ+1}; }
  case 'moveLine': return {...state,boardLines:state.boardLines.map(line=>line.id===action.id?{...line,start:action.start,end:action.end,zIndex:state.nextZ}:line),nextZ:state.nextZ+1};
  case 'deleteLine': return {...state,boardLines:state.boardLines.filter(line=>line.id!==action.id)};
  case 'addPlayer': return { ...state, players: [...state.players, action.player], activePlayerId: state.activePlayerId ?? action.player.id };
  case 'updatePlayer': return { ...state, players: state.players.map(p => p.id === action.id ? { ...p, ...action.changes } : p) };
  case 'deletePlayer': { const player = state.players.find(p => p.id === action.id); const locations = { ...state.cardLocations }; player?.hand.forEach(cardId => { locations[cardId] = { type: 'unplaced' }; }); return { ...state, players: state.players.filter(p => p.id !== action.id), cardLocations: locations, activePlayerId: state.activePlayerId === action.id ? state.players.find(p => p.id !== action.id)?.id : state.activePlayerId }; }
  case 'exchangeCards': { const first = state.players.find(player => player.id === action.firstPlayerId); const second = state.players.find(player => player.id === action.secondPlayerId); if (!first || !second || first.id === second.id || !action.firstCardIds.every(id => first.hand.includes(id)) || !action.secondCardIds.every(id => second.hand.includes(id))) return state; const locations = { ...state.cardLocations }; action.firstCardIds.forEach(id => { locations[id] = { type: 'hand', playerId: second.id }; }); action.secondCardIds.forEach(id => { locations[id] = { type: 'hand', playerId: first.id }; }); return { ...state, players: state.players.map(player => player.id === first.id ? { ...player, hand: [...player.hand.filter(id => !action.firstCardIds.includes(id)), ...action.secondCardIds] } : player.id === second.id ? { ...player, hand: [...player.hand.filter(id => !action.secondCardIds.includes(id)), ...action.firstCardIds] } : player), cardLocations: locations }; }
  case 'importSetup': return { ...state, players: action.players.map(p => ({ ...p, hand: [] })), cards: action.cards, decks: [], dice: [], tokens: [], pawns: [], tableObjects: [], cardLocations: Object.fromEntries(action.cards.map(card => [card.id, { type: 'unplaced' as const }])), activePlayerId: action.players[0]?.id, nextZ: 1 };
  case 'createCards': { const cards: Card[] = []; for (const suit of action.suits.filter(Boolean)) for (const value of action.values.filter(Boolean)) for(let n=0;n<action.copies;n++) cards.push({id:id('card'), suit, value}); return { ...state, cards: [...state.cards,...cards], cardLocations: {...state.cardLocations, ...Object.fromEntries(cards.map(c=>[c.id,{type:'unplaced' as const}]))} }; }
  case 'addCards': { const cards = Array.from({length:action.copies},()=>({id:id('card'),suit:action.suit,value:action.value})); if (!action.position) return {...state,cards:[...state.cards,...cards],cardLocations:{...state.cardLocations,...Object.fromEntries(cards.map(c=>[c.id,{type:'unplaced' as const}]))}}; const objs=cards.map((c,i)=>object('card',c.id,clampObjectPosition(state,'card',{x:action.position!.x+i*18,y:action.position!.y+i*18}),state.nextZ+i)); return {...state,cards:[...state.cards,...cards],tableObjects:[...state.tableObjects,...objs],cardLocations:{...state.cardLocations,...Object.fromEntries(objs.map(o=>[o.refId,{type:'table' as const,objectId:o.id}]))},nextZ:state.nextZ+objs.length}; }
  case 'updateCard': return {...state,cards:state.cards.map(c=>c.id===action.id?{...c,...action.changes}:c)};
  case 'deleteCard': { const s=removeCardEverywhere(state,action.id); const loc={...s.cardLocations}; delete loc[action.id]; return {...s,cards:s.cards.filter(c=>c.id!==action.id),cardLocations:loc}; }
  case 'deleteCards': { let s = state; action.ids.forEach(cardId => { s = removeCardEverywhere(s, cardId); }); const locations = { ...s.cardLocations }; action.ids.forEach(cardId => delete locations[cardId]); return { ...s, cards: s.cards.filter(card => !action.ids.includes(card.id)), cardLocations: locations }; }
  case 'createDeck': { const deck={id:id('deck'),name:action.name,cardIds:action.cardIds}; const s=action.cardIds.reduce((acc,c)=>removeCardEverywhere(acc,c),state); const o=object('deck',deck.id,clampObjectPosition(s,'deck',action.position),s.nextZ); return {...s,decks:[...s.decks,deck],tableObjects:[...s.tableObjects,o],cardLocations:{...s.cardLocations,...Object.fromEntries(action.cardIds.map(c=>[c,{type:'deck' as const,deckId:deck.id}]))},nextZ:s.nextZ+1}; }
  case 'deleteDeck': { const deck = state.decks.find(d => d.id === action.id); const locations = { ...state.cardLocations }; deck?.cardIds.forEach(cardId => { locations[cardId] = { type: 'unplaced' }; }); return {...state,decks:state.decks.filter(d=>d.id!==action.id),tableObjects:state.tableObjects.filter(o=>!(o.type==='deck'&&o.refId===action.id)),cardLocations:locations}; }
  case 'shuffleDeck': return {...state,decks:state.decks.map(d=>d.id===action.id?{...d,cardIds:shuffle(d.cardIds)}:d)};
  case 'drawCard': { const deck=state.decks.find(d=>d.id===action.deckId); const cardId=deck?.cardIds[deck.cardIds.length-1]; if(!deck||!cardId)return state; const active=state.players.find(p=>p.id===state.activePlayerId); const decks=state.decks.map(d=>d.id===deck.id?{...d,cardIds:d.cardIds.slice(0,-1)}:d); if(active?.handEnabled) return {...state,decks,players:state.players.map(p=>p.id===active.id?{...p,hand:[...p.hand,cardId]}:p),cardLocations:{...state.cardLocations,[cardId]:{type:'hand',playerId:active.id}}}; const deckObj=state.tableObjects.find(o=>o.type==='deck'&&o.refId===deck.id); const o=object('card',cardId,clampObjectPosition(state,'card',{x:(deckObj?.position.x??200)+140,y:deckObj?.position.y??200}),state.nextZ); return {...state,decks,tableObjects:[...state.tableObjects,o],cardLocations:{...state.cardLocations,[cardId]:{type:'table',objectId:o.id}},nextZ:state.nextZ+1}; }
  case 'drawCardToTable': { const deck=state.decks.find(d=>d.id===action.deckId); const cardId=deck?.cardIds.at(-1); if(!deck||!cardId)return state; const deckObject=state.tableObjects.find(o=>o.type==='deck'&&o.refId===deck.id); const o=object('card',cardId,clampObjectPosition(state,'card',{x:(deckObject?.position.x??120)+105,y:(deckObject?.position.y??120)+16}),state.nextZ); return {...state,decks:state.decks.map(d=>d.id===deck.id?{...d,cardIds:d.cardIds.slice(0,-1)}:d),tableObjects:[...state.tableObjects,o],cardLocations:{...state.cardLocations,[cardId]:{type:'table',objectId:o.id}},nextZ:state.nextZ+1}; }
  case 'dealCards': { let next = state; for (let n = 0; n < action.count; n++) { const deck = next.decks.find(d => d.id === action.deckId); if (!deck?.cardIds.length) break; next = reducer(next, { type: 'drawCard', deckId: action.deckId }); } return next; }
  case 'dealEvenly': { const recipients = state.players.filter(p => p.handEnabled); if (!recipients.length) return state; let next = state; for (let n = 0; n < action.count; n++) for (const player of recipients) { const deck = next.decks.find(d => d.id === action.deckId); const cardId = deck?.cardIds.at(-1); if (!deck || !cardId) return next; next = reducer(next, { type: 'moveCardToHand', cardId, playerId: player.id }); } return next; }
  case 'moveCardToTable': { const s=removeCardEverywhere(state,action.cardId); const base = action.snap ? { x: Math.round(action.position.x / 30) * 30, y: Math.round(action.position.y / 30) * 30 } : action.position; const stacked = s.tableObjects.filter(o => o.type === 'card' && Math.abs(o.position.x-base.x) < 50 && Math.abs(o.position.y-base.y) < 70).length; const position = clampObjectPosition(s,'card',{ x: base.x + Math.min(stacked, 5) * 13, y: base.y + Math.min(stacked, 5) * 13 }); const o={...object('card',action.cardId,position,s.nextZ),faceDown:action.faceDown}; return {...s,tableObjects:[...s.tableObjects,o],cardLocations:{...s.cardLocations,[action.cardId]:{type:'table',objectId:o.id}},nextZ:s.nextZ+1}; }
  case 'moveCardToHand': { const s = removeCardEverywhere(state, action.cardId); return { ...s, players: s.players.map(player => player.id === action.playerId ? { ...player, hand: [...player.hand, action.cardId] } : player), cardLocations: { ...s.cardLocations, [action.cardId]: { type: 'hand', playerId: action.playerId } } }; }
  case 'returnToDeck': { const s=removeCardEverywhere(state,action.cardId); return {...s,decks:s.decks.map(d=>d.id===action.deckId?{...d,cardIds:[...d.cardIds,action.cardId]}:d),cardLocations:{...s.cardLocations,[action.cardId]:{type:'deck',deckId:action.deckId}}}; }
  case 'moveObject': { const target=state.tableObjects.find(o=>o.id===action.id);if(!target)return state;const raw = action.snap ? { x: Math.round(action.position.x / 30) * 30, y: Math.round(action.position.y / 30) * 30 } : action.position;const position=clampObjectPosition(state,target.type,raw); return {...state,tableObjects:state.tableObjects.map(o=>o.id===action.id?{...o,position,zIndex:state.nextZ}:o),nextZ:state.nextZ+1}; }
  case 'flipTableCard': return { ...state, tableObjects: state.tableObjects.map(object => object.id === action.objectId && object.type === 'card' ? { ...object, faceDown: !object.faceDown } : object) };
  case 'selectPlayer': return {...state,activePlayerId:action.id};
  case 'addDie': {const die={id:id('die'),sides:6,value:1};return {...state,dice:[...state.dice,die],tableObjects:[...state.tableObjects,object('die',die.id,clampObjectPosition(state,'die',action.position),state.nextZ)],nextZ:state.nextZ+1}};
  case 'rollDie': return {...state,dice:state.dice.map(d=>d.id===action.id?{...d,value:Math.floor(Math.random()*d.sides)+1}:d)};
  case 'addToken': {const token={id:id('token'),color:action.color,value:action.value};return {...state,tokens:[...state.tokens,token],tableObjects:[...state.tableObjects,object('token',token.id,clampObjectPosition(state,'token',action.position),state.nextZ)],nextZ:state.nextZ+1}};
  case 'updateToken': return {...state,tokens:state.tokens.map(t=>t.id===action.id?{...t,...action.changes}:t)};
  case 'deleteToken': return {...state,tokens:state.tokens.filter(t=>t.id!==action.id),tableObjects:state.tableObjects.filter(o=>o.refId!==action.id)};
  case 'addPawn': {const pawn={id:id('pawn'),color:action.color,ownerPlayerId:action.ownerPlayerId};return {...state,pawns:[...state.pawns,pawn],tableObjects:[...state.tableObjects,object('pawn',pawn.id,clampObjectPosition(state,'pawn',action.position??{x:220,y:200}),state.nextZ)],nextZ:state.nextZ+1}};
  case 'updatePawn': return {...state,pawns:state.pawns.map(p=>p.id===action.id?{...p,...action.changes}:p)};
  case 'deletePawn': return {...state,pawns:state.pawns.filter(p=>p.id!==action.id),tableObjects:state.tableObjects.filter(o=>o.refId!==action.id)};
  case 'changeScore': return {...state,players:state.players.map(p=>p.id===action.id?{...p,score:p.score+action.amount}:p)};
 }
}
