import { useState } from 'react';
import type { Dispatch, PointerEvent } from 'react';
import type { GameState, Player, TableObject } from '../types/game';
import type { Action } from '../game/reducer';
import { BoardLayer } from '../components/BoardLayer';
import { GameObjectLayer } from '../components/GameObjectLayer';
import { Modal } from '../components/Modal';
import { cardColorClass } from '../utils/cardColor';

const CARD_SIZE={width:84,height:116};
const DECK_SIZE={width:92,height:118};

function clientToBoard(svg:SVGSVGElement,clientX:number,clientY:number){
 const matrix=svg.getScreenCTM();
 if(!matrix)return{x:clientX,y:clientY};
 const point=new DOMPoint(clientX,clientY).matrixTransform(matrix.inverse());
 return{x:point.x,y:point.y};
}

function deckUnderCard(state:GameState,position:{x:number;y:number}){
 let match:TableObject|undefined;
 let bestCoverage=.9;
 for(const deck of state.tableObjects.filter(object=>object.type==='deck')){
  const overlapWidth=Math.max(0,Math.min(position.x+CARD_SIZE.width,deck.position.x+DECK_SIZE.width)-Math.max(position.x,deck.position.x));
  const overlapHeight=Math.max(0,Math.min(position.y+CARD_SIZE.height,deck.position.y+DECK_SIZE.height)-Math.max(position.y,deck.position.y));
  const coverage=overlapWidth*overlapHeight/(CARD_SIZE.width*CARD_SIZE.height);
  if(coverage>=bestCoverage){bestCoverage=coverage;match=deck}
 }
 return match;
}

export function PlayPage({state,dispatch,onSetup}:{state:GameState;dispatch:Dispatch<Action>;onSetup:()=>void}){
 const [selectedIds,setSelectedIds]=useState<string[]>([]); const [add,setAdd]=useState(false); const [dialog,setDialog]=useState<''|'card'|'token'|'pawn'|'deck'>(''); const [hidden,setHidden]=useState<Record<string,boolean>>({}); const [rolling,setRolling]=useState<string>(); const [ghost,setGhost]=useState<{x:number;y:number;back:boolean;count:number}|null>(null); const [selections,setSelections]=useState<Record<string,string[]>>({}); const [dropTargetDeckId,setDropTargetDeckId]=useState<string>();
 const get=(o:TableObject):any=>o.type==='card'?state.cards.find(x=>x.id===o.refId):o.type==='deck'?state.decks.find(x=>x.id===o.refId):o.type==='die'?state.dice.find(x=>x.id===o.refId):o.type==='token'?state.tokens.find(x=>x.id===o.refId):state.pawns.find(x=>x.id===o.refId);
 const drag=(o:TableObject,e:PointerEvent<HTMLDivElement>)=>{e.preventDefault();const svg=e.currentTarget.closest('svg.game-object-layer') as SVGSVGElement|null;if(!svg)return;const moving=selectedIds.includes(o.id)&&selectedIds.length>1?state.tableObjects.filter(x=>selectedIds.includes(x.id)):[o];const origins=moving.map(x=>({id:x.id,p:{...x.position}}));const draggedOrigin=origins.find(origin=>origin.id===o.id)!;const start=clientToBoard(svg,e.clientX,e.clientY);const positionAt=(pointer:globalThis.PointerEvent)=>{const current=clientToBoard(svg,pointer.clientX,pointer.clientY);return{x:draggedOrigin.p.x+current.x-start.x,y:draggedOrigin.p.y+current.y-start.y}};const cleanup=()=>{setDropTargetDeckId(undefined);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end);window.removeEventListener('pointercancel',cancel)};const move=(pointer:globalThis.PointerEvent)=>{const current=clientToBoard(svg,pointer.clientX,pointer.clientY);origins.forEach(origin=>dispatch({type:'moveObject',id:origin.id,position:{x:origin.p.x+current.x-start.x,y:origin.p.y+current.y-start.y},snap:pointer.shiftKey}));setDropTargetDeckId(o.type==='card'?deckUnderCard(state,positionAt(pointer))?.refId:undefined)};const end=(pointer:globalThis.PointerEvent)=>{const target=o.type==='card'?deckUnderCard(state,positionAt(pointer)):undefined;if(target&&Math.hypot(pointer.clientX-e.clientX,pointer.clientY-e.clientY)>4){moving.filter(object=>object.type==='card').forEach(card=>dispatch({type:'returnToDeck',cardId:card.refId,deckId:target.refId,placement:pointer.ctrlKey?'random':'top'}));setSelectedIds(current=>current.filter(id=>!moving.some(object=>object.id===id)))}cleanup()};const cancel=()=>cleanup();window.addEventListener('pointermove',move);window.addEventListener('pointerup',end);window.addEventListener('pointercancel',cancel)};
 const dragHand=(id:string,e:PointerEvent<HTMLButtonElement>)=>{if(e.button!==0&&e.button!==2)return;e.preventDefault();const owner=state.players.find(p=>p.hand.includes(id));const picked=owner&&selections[owner.id]?.includes(id)?selections[owner.id]:[id];const start={x:e.clientX,y:e.clientY},back=e.button===2;const boardPosition=(pointer:globalThis.PointerEvent)=>{const boardElement=document.elementFromPoint(pointer.clientX,pointer.clientY)?.closest('.board') as HTMLElement|null;const svg=boardElement?.querySelector<SVGSVGElement>('.game-object-layer');if(!svg)return;const point=clientToBoard(svg,pointer.clientX,pointer.clientY);return{x:point.x-CARD_SIZE.width/2,y:point.y-CARD_SIZE.height/2}};const cleanup=()=>{setGhost(null);setDropTargetDeckId(undefined);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end);window.removeEventListener('pointercancel',cancel)};const move=(pointer:globalThis.PointerEvent)=>{setGhost({x:pointer.clientX,y:pointer.clientY,back,count:picked.length});const position=boardPosition(pointer);setDropTargetDeckId(position?deckUnderCard(state,position)?.refId:undefined)};const end=(pointer:globalThis.PointerEvent)=>{const base=boardPosition(pointer);if(base&&Math.hypot(pointer.clientX-start.x,pointer.clientY-start.y)>8){const target=deckUnderCard(state,base);if(target)picked.forEach(cardId=>dispatch({type:'returnToDeck',cardId,deckId:target.refId,placement:pointer.ctrlKey?'random':'top'}));else picked.forEach((cardId,index)=>dispatch({type:'moveCardToTable',cardId,position:{x:base.x+(index%5)*18,y:base.y+Math.floor(index/5)*24},faceDown:back,snap:pointer.shiftKey}));if(owner)setSelections(current=>({...current,[owner.id]:[]}))}cleanup()};const cancel=()=>cleanup();window.addEventListener('pointermove',move);window.addEventListener('pointerup',end);window.addEventListener('pointercancel',cancel)};
 const roll=(id:string)=>{if(rolling)return;setRolling(id);setTimeout(()=>{dispatch({type:'rollDie',id});setRolling(undefined)},500)};const choose=(id:string,additive:boolean)=>setSelectedIds(current=>additive?(current.includes(id)?current.filter(x=>x!==id):[...current,id]):[id]);const chosen=state.tableObjects.find(o=>o.id===selectedIds[selectedIds.length-1]);const selectedCardIds=state.tableObjects.filter(o=>selectedIds.includes(o.id)&&o.type==='card').map(o=>o.refId);
 return <main className="play"><aside className="players"><div className="bar"><b>プレイヤー</b><button onClick={onSetup}>設定</button></div>{state.players.map(p=><section key={p.id} className={`player ${p.id===state.activePlayerId?'active':''}`} onClick={()=>dispatch({type:'selectPlayer',id:p.id})}><i style={{background:p.color}}/><strong>{p.name}</strong>{p.scoreEnabled&&<span className="score"><button onClick={()=>dispatch({type:'changeScore',id:p.id,amount:-1})}>−</button>{p.score}<button onClick={()=>dispatch({type:'changeScore',id:p.id,amount:1})}>＋</button></span>}</section>)}</aside><section className="board-wrap"><div className="board" onPointerDown={()=>setSelectedIds([])}><BoardLayer state={state}/><GameObjectLayer state={state} selectedIds={selectedIds} rolling={rolling} dropTargetDeckId={dropTargetDeckId} dispatch={dispatch} onSelect={choose} onDrag={drag} onRoll={roll}/></div>{chosen&&<Menu o={chosen} item={get(chosen)} selectedCardIds={selectedCardIds} state={state} dispatch={dispatch} roll={roll}/>}</section><button className="fab" onClick={()=>setAdd(!add)}>＋</button>{add&&<div className="add-menu">{(['card','deck','die','token','pawn'] as const).map(k=><button key={k} onClick={()=>{setAdd(false);k==='die'?dispatch({type:'addDie',position:{x:300,y:160}}):setDialog(k)}}>{k}</button>)}</div>}<section className="hands">{state.players.filter(p=>p.handEnabled).map(p=><Hand key={p.id} player={p} state={state} dispatch={dispatch} hidden={!!hidden[p.id]} toggle={()=>setHidden({...hidden,[p.id]:!hidden[p.id]})} selected={selections[p.id]??[]} allSelections={selections} setSelected={ids=>setSelections({...selections,[p.id]:ids})} drag={dragHand}/>)}</section>{ghost&&<div className={`drag-ghost ${ghost.back?'face-down':''}`} style={{left:ghost.x,top:ghost.y}}>{ghost.back?'◆':`${ghost.count}枚を置く`}</div>}{dialog&&<Add kind={dialog} state={state} dispatch={dispatch} close={()=>setDialog('')}/>}</main>;
}
function Hand({player,state,dispatch,hidden,toggle,selected,allSelections,setSelected,drag}:{player:Player;state:GameState;dispatch:Dispatch<Action>;hidden:boolean;toggle:()=>void;selected:string[];allSelections:Record<string,string[]>;setSelected:(ids:string[])=>void;drag:(id:string,e:PointerEvent<HTMLButtonElement>)=>void}){
 const [target,setTarget]=useState(state.players.find(candidate=>candidate.id!==player.id)?.id??'');
 const [deck,setDeck]=useState(state.decks[0]?.id??'');
 const pick=(id:string)=>setSelected(selected.includes(id)?selected.filter(cardId=>cardId!==id):[...selected,id]);
 return <div className="hand"><header><span>{player.name} の手札（{player.hand.length}）</span><button onClick={toggle}>{hidden?'見る':'隠す'}</button></header>{!hidden&&<><div>{player.hand.map(id=>{const card=state.cards.find(candidate=>candidate.id===id);return card&&<span className="hand-select" key={id}><input type="checkbox" checked={selected.includes(id)} onChange={()=>pick(id)}/><button className={`hand-card ${cardColorClass(card.suit)} ${selected.includes(id)?'selected':''}`} onContextMenu={event=>event.preventDefault()} onPointerDown={event=>drag(id,event)} onClick={event=>{if(event.shiftKey){event.preventDefault();pick(id)}}}>{card.suit}<b>{card.value}</b><span className="hand-hint">Shift＋クリックで複数選択<br/>ドラッグで表／右ドラッグで裏<br/>山札に重ねて戻す</span></button></span>})}</div>{selected.length>0&&<div className="hand-actions"><select value={target} onChange={event=>setTarget(event.target.value)}>{state.players.filter(candidate=>candidate.id!==player.id).map(candidate=><option value={candidate.id} key={candidate.id}>{candidate.name}</option>)}</select><button onClick={()=>{selected.forEach(cardId=>dispatch({type:'moveCardToHand',cardId,playerId:target}));setSelected([])}}>選択分を渡す</button><button disabled={!allSelections[target]?.length} onClick={()=>{dispatch({type:'exchangeCards',firstPlayerId:player.id,firstCardIds:selected,secondPlayerId:target,secondCardIds:allSelections[target]??[]});setSelected([])}}>選択分を交換</button><select value={deck} onChange={event=>setDeck(event.target.value)}>{state.decks.map(candidate=><option value={candidate.id} key={candidate.id}>{candidate.name}</option>)}</select><button disabled={!deck} onClick={()=>{selected.forEach(cardId=>dispatch({type:'returnToDeck',cardId,deckId:deck}));setSelected([])}}>選択分を山札へ</button></div>}</>}</div>;
}
function Menu({o,item,selectedCardIds,state,dispatch,roll}:{o:TableObject;item:any;selectedCardIds:string[];state:GameState;dispatch:Dispatch<Action>;roll:(id:string)=>void}){const [count,setCount]=useState(1),[player,setPlayer]=useState(state.activePlayerId??''),[deck,setDeck]=useState(state.decks[0]?.id??'');const cards=selectedCardIds.length?selectedCardIds:[item?.id].filter(Boolean);return <div className="object-menu">{o.type==='deck'&&<><button onClick={()=>dispatch({type:'shuffleDeck',id:item.id})}>シャッフル</button><button onClick={()=>dispatch({type:'drawCard',deckId:item.id})}>1枚引く</button><button onClick={()=>dispatch({type:'drawCardToTable',deckId:item.id})}>場に出す</button><input type="number" min="1" value={count} onChange={e=>setCount(Math.max(1,+e.target.value))}/><button onClick={()=>dispatch({type:'dealCards',deckId:item.id,count})}>操作中の人へ配る</button><button onClick={()=>dispatch({type:'dealEvenly',deckId:item.id,count})}>全員へ配る</button></>}{o.type==='die'&&<button onClick={()=>roll(item.id)}>Roll</button>}{o.type==='token'&&<><button onClick={()=>dispatch({type:'updateToken',id:item.id,changes:{value:item.value+1}})}>+1</button><button onClick={()=>dispatch({type:'updateToken',id:item.id,changes:{value:item.value-1}})}>-1</button></>}{o.type==='card'&&<><b>{cards.length}枚選択</b><button onClick={()=>state.tableObjects.filter(x=>x.type==='card'&&cards.includes(x.refId)).forEach(x=>dispatch({type:'flipTableCard',objectId:x.id}))}>選択分を反転</button><select value={player} onChange={e=>setPlayer(e.target.value)}>{state.players.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><button onClick={()=>cards.forEach(cardId=>dispatch({type:'moveCardToHand',cardId,playerId:player}))}>選択分を手札へ</button><select value={deck} onChange={e=>setDeck(e.target.value)}>{state.decks.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select><button onClick={()=>cards.forEach(cardId=>dispatch({type:'returnToDeck',cardId,deckId:deck}))}>選択分を山札へ</button></>}</div>}
function Add({kind,state,dispatch,close}:{kind:'card'|'token'|'pawn'|'deck';state:GameState;dispatch:Dispatch<Action>;close:()=>void}){
 const isPlayerPiece=kind==='token'||kind==='pawn';
 const initialPlayer=state.players.find(player=>player.id===state.activePlayerId)??state.players[0];
 const [a,setA]=useState(kind==='card'?'joker':isPlayerPiece?(initialPlayer?.color??'#e3a52b'):'山札');
 const [b,setB]=useState('1');
 const [ownerId,setOwnerId]=useState(initialPlayer?.id??'');
 const selectPlayerColor=(player:Player)=>{setA(player.color);setOwnerId(player.id)};
 const addPiece=(color:string,position:{x:number;y:number},playerId?:string)=>{
  if(kind==='token')dispatch({type:'addToken',color,value:+b||0,position});
  if(kind==='pawn')dispatch({type:'addPawn',color,ownerPlayerId:playerId,position});
 };
 const addForEveryPlayer=()=>{state.players.forEach((player,index)=>addPiece(player.color,{x:220+(index%8)*82,y:170+Math.floor(index/8)*88},player.id));close()};
 const addOne=()=>{if(kind==='card')dispatch({type:'addCards',suit:a,value:b,copies:1,position:{x:260,y:180}});if(isPlayerPiece)addPiece(a,{x:280,y:190},ownerId||undefined);if(kind==='deck')dispatch({type:'createDeck',name:a,cardIds:state.cards.filter(c=>state.cardLocations[c.id]?.type==='unplaced').map(c=>c.id),position:{x:100,y:150}});close()};
 return <Modal title={`${kind==='token'?'チップ':kind==='pawn'?'コマ':kind==='card'?'カード':'山札'}を追加`} onClose={close}>
  {isPlayerPiece?<>
   <p className="piece-color-label">プレイヤーカラーから選択</p>
   <div className="player-color-list">{state.players.map(player=><button key={player.id} type="button" className={ownerId===player.id?'selected':''} onClick={()=>selectPlayerColor(player)}><i style={{background:player.color}}/>{player.name}</button>)}</div>
   <label className="piece-color-custom">色を調整<input type="color" value={a} onChange={e=>{setA(e.target.value);setOwnerId('')}}/></label>
   {kind==='token'&&<label>数値<input type="number" value={b} onChange={e=>setB(e.target.value)}/></label>}
   <div className="piece-add-actions"><button className="primary" onClick={addOne}>選択した色で1個追加</button><button className="secondary" disabled={!state.players.length} onClick={addForEveryPlayer}>人数分を追加（{state.players.length}個）</button></div>
  </>:<><label>{kind==='card'?'スート':'山札名'}<input value={a} onChange={e=>setA(e.target.value)}/></label>{kind==='card'&&<label>値<input value={b} onChange={e=>setB(e.target.value)}/></label>}<button className="primary" onClick={addOne}>追加</button></>}
 </Modal>
}
