import { useRef, useState } from 'react';
import type { Dispatch } from 'react';
import type { GameState, Player } from '../types/game';
import type { Action } from '../game/reducer';
import { id } from '../utils/id';
const colors=['#d64b4b','#397bd8','#e3a52b','#4ca66b','#8556b8'];
export function SetupPage({state,dispatch,onStart}:{state:GameState;dispatch:Dispatch<Action>;onStart:()=>void}){
 const [suits,setSuits]=useState(['赤','青']); const [values,setValues]=useState(['1','2','3']); const [copies,setCopies]=useState(1);
 const [confirmDelete,setConfirmDelete]=useState<string>();
 const fileInput = useRef<HTMLInputElement>(null);
 const cardGroups = Object.values(state.cards.reduce<Record<string,{key:string;suit:string;value:string|number;ids:string[]}>>((groups, card) => { const key=`${card.suit} / ${card.value}`; (groups[key] ??= {key,suit:card.suit,value:card.value,ids:[]}).ids.push(card.id); return groups; }, {}));
 const addPlayer=()=>{const p:Player={id:id('player'),name:`プレイヤー ${state.players.length+1}`,color:colors[state.players.length%colors.length],handEnabled:true,scoreEnabled:true,roleEnabled:false,hand:[],score:0};dispatch({type:'addPlayer',player:p})};
 const update=(p:Player,changes:Partial<Player>)=>dispatch({type:'updatePlayer',id:p.id,changes});
 const exportSetup=()=>{ const content=JSON.stringify({version:1,players:state.players,cards:state.cards},null,2); const url=URL.createObjectURL(new Blob([content],{type:'application/json'})); const link=document.createElement('a'); link.href=url; link.download='boardgame-setup.json'; link.click(); URL.revokeObjectURL(url); };
 const importSetup=async(file:File)=>{ try { const data=JSON.parse(await file.text()); if(!Array.isArray(data.players)||!Array.isArray(data.cards)) throw new Error('形式が正しくありません'); dispatch({type:'importSetup',players:data.players,cards:data.cards}); } catch { alert('読み込めませんでした。設定JSONファイルを選択してください。'); } };
 const field=(items:string[],set:(x:string[])=>void,label:string)=><label>{label}<div className="chips">{items.map((x,i)=><input key={i} value={x} onChange={e=>set(items.map((v,j)=>j===i?e.target.value:v))}/>)}<button type="button" onClick={()=>set([...items,''])}>＋</button></div></label>;
 return <main className="setup"><div className="intro"><p className="eyebrow">BOARD GAME PLAYTEST</p><h1>ゲームを組み立てる</h1><p>ルールを縛らず、カードやコマを自由に置いて試遊できるワークスペースです。</p><div className="setup-io"><button className="secondary" onClick={exportSetup}>設定を出力</button><button className="secondary" onClick={()=>fileInput.current?.click()}>設定を読み込む</button><input ref={fileInput} className="file-input" type="file" accept="application/json,.json" onChange={e=>{const file=e.target.files?.[0];if(file)importSetup(file);e.currentTarget.value=''}}/></div></div><section className="setup-grid"><article><h2>プレイヤー</h2>{state.players.map(p=><div className="player-edit" key={p.id}><input type="color" value={p.color} onChange={e=>update(p,{color:e.target.value})}/><input value={p.name} onChange={e=>update(p,{name:e.target.value})}/><button onClick={()=>dispatch({type:'deletePlayer',id:p.id})}>削除</button><div className="toggles">{(['handEnabled','scoreEnabled','roleEnabled'] as const).map(k=><label key={k}><input type="checkbox" checked={p[k]} onChange={e=>update(p,{[k]:e.target.checked})}/>{k==='handEnabled'?'手札':k==='scoreEnabled'?'得点':'役職'}</label>)}</div></div>)}<button className="secondary" onClick={addPlayer}>＋ プレイヤー追加</button></article><article><h2>カードセット作成</h2>{field(suits,setSuits,'Suit')}{field(values,setValues,'Value')}<label>各カードの枚数<input type="number" min="1" value={copies} onChange={e=>setCopies(Math.max(1,Number(e.target.value)))}/></label><button className="primary" onClick={()=>dispatch({type:'createCards',suits,values,copies})}>カードを生成</button><p className="muted">現在 {state.cards.length} 枚のカード</p></article><article><h2>山札</h2><p>生成済みのカードをひとつの山札にまとめて、試遊中にシャッフル・ドローできます。</p><button className="secondary" disabled={!state.cards.length} onClick={()=>dispatch({type:'createDeck',name:`山札 ${state.decks.length+1}`,cardIds:state.cards.filter(c=>state.cardLocations[c.id]?.type==='unplaced').map(c=>c.id),position:{x:80,y:100}})}>未配置カードで山札を作成</button><p className="muted">{state.decks.length} 個の山札</p></article></section><section className="card-summary"><h2>現在のカード一覧</h2>{cardGroups.length===0?<p className="muted">まだカードはありません。</p>:<div className="summary-list">{cardGroups.map(group=><div className="summary-row" key={group.key}><span className={`suit-dot suit-${group.suit}`}/><span>{group.suit} / {group.value}</span><strong>× {group.ids.length}</strong><button className="danger" onClick={()=>confirmDelete===group.key?(dispatch({type:'deleteCards',ids:group.ids}),setConfirmDelete(undefined)):setConfirmDelete(group.key)}>{confirmDelete===group.key?'削除を確定':'削除'}</button></div>)}</div>}</section><button className="start" onClick={onStart}>試遊を開始 →</button></main>
}
