import { useEffect, useState } from 'react';

const MIN_ZOOM=.75;
const MAX_ZOOM=4;
const ZOOM_STEP=.1;
const clampZoom=(value:number)=>Math.min(MAX_ZOOM,Math.max(MIN_ZOOM,Math.round(value*10)/10));

export function BoardZoom(){
 const [zoom,setZoom]=useState(1);
 useEffect(()=>{const board=document.querySelector<HTMLElement>('.play .board');const wrap=board?.parentElement;const svg=board?.querySelector<SVGSVGElement>('.play-board-layer');if(!board||!wrap)return;const resize=()=>{const style=getComputedStyle(wrap);const availableWidth=Math.max(1,wrap.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight));const availableHeight=Math.max(1,wrap.clientHeight-parseFloat(style.paddingTop)-parseFloat(style.paddingBottom));const logicalWidth=svg?.viewBox.baseVal.width||900,logicalHeight=svg?.viewBox.baseVal.height||600;const ratio=logicalWidth/logicalHeight;const baseWidth=Math.min(availableWidth,availableHeight*ratio);const baseHeight=baseWidth/ratio;board.style.width=`${baseWidth*zoom}px`;board.style.height=`${baseHeight*zoom}px`;board.style.aspectRatio=`${logicalWidth}/${logicalHeight}`;wrap.style.justifyContent=zoom>1?'flex-start':'center';wrap.style.alignItems=zoom>1?'flex-start':'center'};resize();const observer=new ResizeObserver(resize);observer.observe(wrap);return()=>{observer.disconnect();board.style.removeProperty('width');board.style.removeProperty('height');board.style.removeProperty('aspect-ratio');wrap.style.removeProperty('justify-content');wrap.style.removeProperty('align-items')}},[zoom]);
 const change=(value:number)=>setZoom(clampZoom(value));
 useEffect(()=>{const zoomBoard=(event:WheelEvent)=>{if(!event.ctrlKey)return;event.preventDefault();setZoom(current=>clampZoom(current+(event.deltaY<0?ZOOM_STEP:-ZOOM_STEP)))};window.addEventListener('wheel',zoomBoard,{passive:false,capture:true});return()=>window.removeEventListener('wheel',zoomBoard,{capture:true})},[]);
 useEffect(()=>{const wrap=document.querySelector<HTMLElement>('.play .board-wrap');if(!wrap)return;let space=false;let cleanup:undefined|(()=>void);const editable=(target:EventTarget|null)=>target instanceof HTMLElement&&!!target.closest('input,textarea,select,button');const keyDown=(e:KeyboardEvent)=>{if(e.code==='Space'&&!editable(e.target)){space=true;document.body.dataset.panMode='true';wrap.classList.add('pan-ready');e.preventDefault()}};const keyUp=(e:KeyboardEvent)=>{if(e.code==='Space'){space=false;delete document.body.dataset.panMode;wrap.classList.remove('pan-ready')}};const start=(e:globalThis.PointerEvent)=>{if(!(e.button===1||(e.button===0&&space)))return;e.preventDefault();e.stopPropagation();const origin={x:e.clientX,y:e.clientY,left:wrap.scrollLeft,top:wrap.scrollTop};wrap.classList.add('panning');const move=(v:globalThis.PointerEvent)=>{wrap.scrollLeft=origin.left-(v.clientX-origin.x);wrap.scrollTop=origin.top-(v.clientY-origin.y)};const end=()=>{wrap.classList.remove('panning');window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',end);cleanup=end};window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);wrap.addEventListener('pointerdown',start,true);return()=>{window.removeEventListener('keydown',keyDown);window.removeEventListener('keyup',keyUp);wrap.removeEventListener('pointerdown',start,true);cleanup?.();delete document.body.dataset.panMode}},[]);
 return <div className="board-zoom" aria-label="盤面の拡大縮小" title="Ctrl＋ホイールでも盤面を拡大・縮小できます"><button onClick={()=>change(zoom-ZOOM_STEP)} disabled={zoom<=MIN_ZOOM} title="縮小">−</button><span className="zoom-value" aria-live="polite">{Math.round(zoom*100)}%</span><button onClick={()=>change(zoom+ZOOM_STEP)} disabled={zoom>=MAX_ZOOM} title="拡大">＋</button><button className="zoom-fit" onClick={()=>change(1)} disabled={zoom===1} title="盤面全体を表示領域に合わせる">フィット</button></div>
}
