import type { Dispatch, PointerEvent } from 'react';
import type { Action } from '../game/reducer';
import type { GameState, TableObject } from '../types/game';

const size={card:{w:84,h:116},deck:{w:92,h:118},die:{w:62,h:62},token:{w:65,h:65},pawn:{w:44,h:58}};
export function GameObjectLayer({state,selectedIds,rolling,dispatch,onSelect,onDrag}:{state:GameState;selectedIds:string[];rolling?:string;dispatch:Dispatch<Action>;onSelect:(id:string,additive:boolean)=>void;onDrag:(o:TableObject,e:PointerEvent<HTMLDivElement>)=>void}){
 const board=state.boards[0]; const width=board?.width??900,height=board?.height??600;
 const get=(o:TableObject):any=>o.type==='card'?state.cards.find(x=>x.id===o.refId):o.type==='deck'?state.decks.find(x=>x.id===o.refId):o.type==='die'?state.dice.find(x=>x.id===o.refId):o.type==='token'?state.tokens.find(x=>x.id===o.refId):state.pawns.find(x=>x.id===o.refId);
 return <svg className="game-object-layer" viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="xMidYMid meet">{[...state.tableObjects].sort((a,b)=>a.zIndex-b.zIndex).map(o=>{const v=get(o);if(!v)return null;const s=size[o.type];const content=o.type==='card'?(o.faceDown?<span className="card-back">◆</span>:<><b>{v.suit}</b><strong>{v.value}</strong></>):o.type==='deck'?<><strong>{v.name}</strong><small>{v.cardIds.length} 枚</small></>:o.type==='die'?<strong>{v.value}</strong>:o.type==='token'?<><i style={{background:v.color}}/><strong>{v.value}</strong></>:<i style={{background:v.color}}/>;return <foreignObject key={o.id} x={o.position.x} y={o.position.y} width={s.w} height={s.h} overflow="visible"><div className={`piece svg-piece ${o.type} ${o.faceDown?'face-down':''} ${rolling===o.refId?'rolling':''} ${selectedIds.includes(o.id)?'selected':''}`} onDoubleClick={()=>o.type==='card'?dispatch({type:'flipTableCard',objectId:o.id}):o.type==='deck'&&dispatch({type:'drawCardToTable',deckId:o.refId})} onPointerDown={e=>{if(e.button===1||document.body.dataset.panMode==='true')return;e.stopPropagation();onSelect(o.id,o.type==='card'&&e.shiftKey);onDrag(o,e)}}>{content}{o.type==='card'&&<span className="card-hint">Shift＋クリックで複数選択<br/>ダブルクリックで反転</span>}{o.type==='deck'&&<span className="card-hint">ダブルクリックで場に出す</span>}</div></foreignObject>})}</svg>
}
